voxelpaint: main.cpp camera.o cursor.o voxel.o world.o
	g++ -Wall main.cpp camera.o cursor.o voxel.o world.o -o voxelpaint

camera.o: camera.cpp
	g++ -Wall -c camera.cpp -o camera.o

cursor.o: cursor.cpp
	g++ -Wall -c cursor.cpp -o cursor.o

voxel.o: voxel.cpp
	g++ -Wall -c voxel.cpp -o voxel.o

world.o: world.cpp
	g++ -Wall -c world.cpp -o world.o
